// src/app/skills/skills.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { MediaChange, MediaObserver } from '@angular/flex-layout';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-skills',
  templateUrl: './skills.component.html',
  styleUrls: ['./skills.component.scss']
})
export class SkillsComponent implements OnDestroy {

  subscriptions: Subscription[] = []
  columnNum: number = 8

  constructor(media: MediaObserver) {
    this.subscriptions.push(media.asObservable().subscribe((change: MediaChange[]) => {
      if (change[0].mqAlias == 'xs') {
        this.columnNum = 2
      } else if (change[0].mqAlias == 'sm') {
        this.columnNum = 5
      } else if (change[0].mqAlias == 'md') {
        this.columnNum = 7
      } else if (change[0].mqAlias == 'lg') {
        this.columnNum = 10
      } else if (change[0].mqAlias == 'xl') {
        this.columnNum = 15
      } else {
        this.columnNum = 20
      }
    }))
  }

  skillTree = [
    {
      title: 'Web',
      skills: [
        {
          image: '/static/images/nodejs.jpg',
          title: 'Node.js'
        },
        {
          image: '/static/images/angular.jpg',
          title: 'Angular'
        },
        {
          image: '/static/images/html.jpg',
          title: 'HTML'
        },
        {
          image: '/static/images/css.jpg',
          title: 'CSS'
        },
        {
          image: '/static/images/javascript.jpg',
          title: 'JavaScript'
        },
        {
          image: '/static/images/typescript.jpg',
          title: 'TypeScript'
        }
      ]
    },
    {
      title: 'Mobile',
      skills: [
        {
          image: '/static/images/flutter.jpg',
          title: 'Flutter'
        }
      ]
    },
    {
      title: 'Database',
      skills: [
        {
          image: '/static/images/mongodb.jpg',
          title: 'MongoDB'
        },
        {
          image: '/static/images/mysql.jpg',
          title: 'MySQL'
        },
        {
          image: '/static/images/postgresql.jpg',
          title: 'PostgreSQL'
        },
      ]
    },
    {
      title: 'Tools',
      skills: [
        {
          image: '/static/images/sublime.jpg',
          title: 'Sublime'
        },
        {
          image: '/static/images/vs.jpg',
          title: 'VS'
        },
        {
          image: '/static/images/vscode.jpg',
          title: 'VS Code'
        }
      ]
    },
    {
      title: 'Platforms',
      skills: [
        {
          image: '/static/images/apigee.jpg',
          title: 'Apigee'
        },
        {
          image: '/static/images/concourse.jpg',
          title: 'Concourse'
        },
        {
          image: '/static/images/heroku.jpg',
          title: 'Heroku'
        },
        {
          image: '/static/images/jira.jpg',
          title: 'Jira'
        },
        {
          image: '/static/images/pcf.jpg',
          title: 'PCF'
        },
        {
          image: '/static/images/servicenow.jpg',
          title: 'ServiceNOW'
        }
      ]
    },
    {
      title: 'Other',
      skills: [
        {
          image: '/static/images/bash.jpg',
          title: 'Bash'
        },
        {
          image: '/static/images/cpp.jpg',
          title: 'C++'
        },
        {
          image: '/static/images/git.jpg',
          title: 'Git'
        },
        {
          image: '/static/images/java.jpg',
          title: 'Java'
        },
        {
          image: '/static/images/linux.jpg',
          title: 'Linux'
        },
        {
          image: '/static/images/photoshop.jpg',
          title: 'Photoshop'
        }
      ]
    }
  ]

  ngOnDestroy() {
    this.subscriptions.forEach(sub => sub.unsubscribe())
  }

}

<div fxLayout="column" fxLayoutGap="1em">
    <div *ngFor="let category of skillTree" fxLayout="column" fxLayoutGap="1em">
        <div fxLayout="row" fxLayoutAlign.lt-sm="center center" class="fadeIntoView">
            <h2>{{category.title}}</h2>
        </div>
        <mat-grid-list [cols]="columnNum" rowHeight="9em">
            <mat-grid-tile *ngFor="let skill of category.skills" class="fadeIntoView">
                <div fxLayout="column" fxLayoutAlign="center center" fxLayoutGap="0.5em">
                    <img [alt]="skill.title + ' logo'" [src]="skill.image" class="logo">
                    <small>{{skill.title}}</small>
                </div>
            </mat-grid-tile>
        </mat-grid-list>
    </div>
</div>

// src/components/Skills/Skills.tsx
import './Skills.css'
import Skill from './Skill//Skill'
import nodejs from '../../assets/images/nodejs.jpg'
import angular from '../../assets/images/angular.jpg'
import react from '../../assets/images/react.jpg'
import html from '../../assets/images/html.jpg'
import css from '../../assets/images/css.jpg'
import javascript from '../../assets/images/javascript.jpg'
import typescript from '../../assets/images/typescript.jpg'
import flutter from '../../assets/images/flutter.jpg'
import mongodb from '../../assets/images/mongodb.jpg'
import mysql from '../../assets/images/mysql.jpg'
import postgresql from '../../assets/images/postgresql.jpg'
import sublime from '../../assets/images/sublime.jpg'
import vs from '../../assets/images/vs.jpg'
import vscode from '../../assets/images/vscode.jpg'
import apigee from '../../assets/images/apigee.jpg'
import concourse from '../../assets/images/concourse.jpg'
import heroku from '../../assets/images/heroku.jpg'
import jira from '../../assets/images/jira.jpg'
import pcf from '../../assets/images/pcf.jpg'
import servicenow from '../../assets/images/servicenow.jpg'
import bash from '../../assets/images/bash.jpg'
import cpp from '../../assets/images/cpp.jpg'
import git from '../../assets/images/git.jpg'
import java from '../../assets/images/java.jpg'
import linux from '../../assets/images/linux.jpg'
import photoshop from '../../assets/images/photoshop.jpg'

const Skills = () => {
    return (
        <div className="skillGrid">
            <Skill alt="nodejs" image={nodejs}></Skill>
            <Skill alt="angular" image={angular}></Skill>
            <Skill alt="react" image={react}></Skill>
            <Skill alt="html" image={html}></Skill>
            <Skill alt="css" image={css}></Skill>
            <Skill alt="javascript" image={javascript}></Skill>
            <Skill alt="typescript" image={typescript}></Skill>
            <Skill alt="flutter" image={flutter}></Skill>
            <Skill alt="mongodb" image={mongodb}></Skill>
            <Skill alt="mysql" image={mysql}></Skill>
            <Skill alt="postgresql" image={postgresql}></Skill>
            <Skill alt="sublime" image={sublime}></Skill>
            <Skill alt="vs" image={vs}></Skill>
            <Skill alt="vscode" image={vscode}></Skill>
            <Skill alt="apigee" image={apigee}></Skill>
            <Skill alt="concourse" image={concourse}></Skill>
            <Skill alt="heroku" image={heroku}></Skill>
            <Skill alt="jira" image={jira}></Skill>
            <Skill alt="pcf" image={pcf}></Skill>
            <Skill alt="servicenow" image={servicenow}></Skill>
            <Skill alt="bash" image={bash}></Skill>
            <Skill alt="cpp" image={cpp}></Skill>
            <Skill alt="git" image={git}></Skill>
            <Skill alt="java" image={java}></Skill>
            <Skill alt="linux" image={linux}></Skill>
            <Skill alt="photoshop" image={photoshop}></Skill>
        </div>
    );
};

export default Skills;
