// src/app/home/home.component.ts
import { AfterViewInit, Component, ElementRef, Input, OnInit, ViewChild } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  imageLoaded: boolean = false

  descriptionString = ''
  showCaret = false
  overrideShowCaret = false

  constructor() { }

  sleep(timeout: number): Promise<void> {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve()
      }, timeout);
    })
  }

  ngOnInit(): void { }

  async typewriteDescriptions() {
    this.caretHeartbeat()
    while (true) {
      for (let i = 0; i < this.descriptions.length; i++) {
        this.descriptionString = ''
        this.overrideShowCaret = true
        for (let j = 0; j < this.descriptions[i].length; j++) {
          this.descriptionString += this.descriptions[i][j]
          await this.sleep(Math.random() * 150)
        }
        this.overrideShowCaret = false
        await this.sleep(3000)
        this.overrideShowCaret = true
        while (this.descriptionString.length > 0) {
          this.descriptionString = this.descriptionString.slice(0, this.descriptionString.length - 1)
          await this.sleep(20)
        }
        this.overrideShowCaret = false
      }
    }
  }

  async caretHeartbeat() {
    while (true) {
      this.showCaret = !this.showCaret
      await this.sleep(1000)
    }
  }

  loaded() {
    this.imageLoaded = true
    this.typewriteDescriptions()
  }

  descriptions = [
    'a Computer Science Student.',
    'interested in Web and App development.',
    'located in Toronto 🇨🇦.'
  ]
}

<div id="about" class="fillHeight">
    <app-top-bar></app-top-bar>
    <div fxLayout="column">
        <div class="about lightBackground" [ngClass.lt-sm]="'centerText'" fxLayout="column" fxLayoutGap="1em"
            fxLayoutAlign="center center">
            <div fxLayout="column" fxLayoutGap="2em" fxLayoutAlign="center center" fxFlex="100%">
                <div fxLayout="row" fxLayout.lt-sm="column" fxLayoutGap="3em" fxLayoutGap.lt-sm="1em"
                    fxLayoutAlign="center center">
                    <img alt="Photo of Imran Remtulla" src="/static/images/me.jpg" class="me fadeIn" (load)="showMe()">
                    <div fxLayout="column" fxLayoutGap="1em">
                        <span>Hi <h1>I'm <span class="accentedText">Imran Remtulla</span></h1></span>
                        <small>I'm {{descriptionString}}<span class="accentedText bold">{{showCaret || overrideShowCaret
                                ?
                                '|' :
                                ''}}</span></small>
                    </div>
                </div>
                <div fxLayout="row" fxLayoutGap="1em" fxLayoutAlign="center end" class="links">
                    <a mat-icon-button aria-label="Link to email me" href="mailto:iremtulla15@gmail.com"
                        rel="noreferrer" target="_blank">
                        <mat-icon svgIcon="email"></mat-icon>
                    </a>
                    <a mat-icon-button aria-label="My Github profile" href="https://github.com/ImranR98"
                        rel="noreferrer" target="_blank">
                        <mat-icon svgIcon="github"></mat-icon>
                    </a>
                    <a mat-icon-button aria-label="My LinkedIn profile" href="https://www.linkedin.com/in/iremtulla/"
                        rel="noreferrer" target="_blank">
                        <mat-icon svgIcon="linkedin"></mat-icon>
                    </a>
                    <a mat-icon-button aria-label="My Medium page" href="https://medium.com/@imranr.dev"
                        rel="noreferrer" target="_blank">
                        <mat-icon svgIcon="medium"></mat-icon>
                    </a>
                </div>
            </div>
            <p class="onlyExtended floating">
                <mat-icon svgIcon="down"></mat-icon>
            </p>
        </div>
        <div id="work" class="stdPadding" fxLayout="column" fxLayoutGap="1em">
            <div fxLayout="column" fxLayoutGap="1em">
                <div fxLayout="column" fxLayoutAlign.lt-sm="center center" class="fadeIntoView">
                    <h1>Work</h1>
                </div>
                <div fxLayout="row" fxLayout.lt-md="column" fxLayoutGap="3em" class="stdPadding">
                    <div fxLayout="column" fxLayoutGap="1em" fxFlex="100%">
                        <div fxLayout="row" fxLayoutGap="1em" fxLayoutAlign="default center" class="fadeIntoView">
                            <img alt="Manulife Financial logo" src="/static/images/manulife.jpg" class="logo">
                            <div fxLayout="column" fxLayoutGap="0.5em">
                                <div fxLayout="column">
                                    <h2>Manulife Financial</h2>
                                    <p>Visiting Platform Reliability Engineer - Co-op</p>
                                </div>
                                <small>September - December 2019</small>
                            </div>
                        </div>
                    </div>
                    <div fxLayout="column" fxLayoutGap="1em" fxFlex="100%">
                        <div fxLayout="row" fxLayoutGap="1em" fxLayoutAlign="default center" class="fadeIntoView">
                            <img alt="Seneca College Logo" src="/static/images/seneca.jpg" class="logo">
                            <div fxLayout="column" fxLayoutGap="0.5em">
                                <div fxLayout="column">
                                    <h2>Seneca College</h2>
                                    <p>Programmer - Co-op</p>
                                </div>
                                <small>September - December 2019</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <mat-divider class="fadeIntoView"></mat-divider>
        <div id="studies" class="stdPadding" fxLayout="column" fxLayoutGap="1em">
            <div fxLayout="column" fxLayoutGap="1em">
                <div fxLayout="column" fxLayoutAlign.lt-sm="center center" class="fadeIntoView">
                    <h1>Studies</h1>
                </div>
                <div fxLayout="row" fxLayout.lt-md="column" fxLayoutGap="3em" class="stdPadding">
                    <div fxLayout="column" fxLayoutGap="1em" fxFlex="100%">
                        <div fxLayout="row" fxLayoutGap="1em" fxLayoutAlign="default center" class="fadeIntoView">
                            <img alt="Ryerson University logo" src="/static/images/ryerson.jpg" class="logo">
                            <div fxLayout="column" fxLayoutGap="0.5em">
                                <div fxLayout="column">
                                    <h2>Ryerson University</h2>
                                    <p>Computer Science (BSc)</p>
                                </div>
                                <small>September 2020 - December 2022</small>
                            </div>
                        </div>
                    </div>
                    <div fxLayout="column" fxLayoutGap="1em" fxFlex="100%">
                        <div fxLayout="row" fxLayoutGap="1em" fxLayoutAlign="default center" class="fadeIntoView">
                            <img alt="Seneca College logo" src="/static/images/seneca.jpg" class="logo">
                            <div fxLayout="column" fxLayoutGap="0.5em">
                                <div fxLayout="column">
                                    <h2>Seneca College</h2>
                                    <p>Computer Programming and Analysis (Ontario College Advanced Diploma)</p>
                                </div>
                                <small>September 2017 - December 2020</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <mat-divider class="fadeIntoView"></mat-divider>
        <div id="projects" class="stdPadding" fxLayout="column" fxLayoutGap="1em">
            <div fxLayout="column" fxLayoutGap="1em">
                <div fxLayout="column" fxLayoutAlign.lt-sm="center center" class="fadeIntoView">
                    <h1>Projects</h1>
                </div>
                <div fxLayout="row" fxLayout.lt-md="column" fxLayoutGap="3em" class="stdPadding">
                    <div fxLayout="column" fxLayoutGap="1em" fxFlex="100%">
                        <div fxLayout="row" fxLayoutGap="1em" fxLayoutAlign="default center" class="fadeIntoView">
                            <img alt="Letter A picture" src="/static/images/andika.jpg" class="logo">
                            <div fxLayout="column" fxLayoutGap="0.5em">
                                <div fxLayout="column">
                                    <h2>Andika</h2>
                                    <p>Note taking Web app made with Angular, Node.js and PostgreSQL</p>
                                </div>
                                <small><a rel="noreferrer" href="https://github.com/ImranR98/andika"
                                        target="_blank">GitHub</a></small>
                            </div>
                        </div>
                    </div>
                    <div fxLayout="column" fxLayoutGap="1em" fxFlex="100%">
                        <div fxLayout="row" fxLayoutGap="1em" fxLayoutAlign="default center" class="fadeIntoView">
                            <img alt="TinyStock Logo" src="/static/images/tinystock.jpg" class="logo">
                            <div fxLayout="column" fxLayoutGap="0.5em">
                                <div fxLayout="column">
                                    <h2>TinyStock</h2>
                                    <p>Minimal stock keeping desktop App built with Angular, Node.js and Electron</p>
                                </div>
                                <small><a rel="noreferrer" href="https://github.com/ImranR98/TinyStock"
                                        target="_blank">GitHub</a></small>
                            </div>
                        </div>
                    </div>
                </div>
                <div fxLayout="row" fxLayout.lt-md="column" fxLayoutGap="3em" class="stdPadding">
                    <div fxLayout="column" fxLayoutGap="1em" fxFlex="100%">
                        <div fxLayout="row" fxLayoutGap="1em" fxLayoutAlign="default center" class="fadeIntoView">
                            <img alt="Tuma Logo" src="/static/images/tuma.jpg" class="logo">
                            <div fxLayout="column" fxLayoutGap="0.5em">
                                <div fxLayout="column">
                                    <h2>Tuma</h2>
                                    <p>Upload files to SFTP servers - Made with Flutter</p>
                                </div>
                                <small><a rel="noreferrer" href="https://github.com/ImranR98/Tuma"
                                        target="_blank">GitHub</a></small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <mat-divider class="fadeIntoView"></mat-divider>
        <div id="skills" class="stdPadding" fxLayout="column" fxLayoutGap="1em">
            <div fxLayout="column" fxLayoutGap="1em">
                <div fxLayout="column" fxLayoutAlign.lt-sm="center center" class="fadeIntoView">
                    <h1>Skills</h1>
                </div>
                <div fxLayout="column" fxLayoutGap="1em">
                    <div *ngFor="let category of skillTree" fxLayout="column" fxLayoutGap="1em">
                        <div fxLayout="row" fxLayoutAlign.lt-sm="center center" class="fadeIntoView">
                            <h2>{{category.title}}</h2>
                        </div>
                        <mat-grid-list [cols]="columnNum" rowHeight="9em">
                            <mat-grid-tile *ngFor="let skill of category.skills" class="fadeIntoView">
                                <div fxLayout="column" fxLayoutAlign="center center" fxLayoutGap="0.5em">
                                    <img [alt]="skill.title + ' logo'" [src]="skill.image" class="logo">
                                    <small>{{skill.title}}</small>
                                </div>
                            </mat-grid-tile>
                        </mat-grid-list>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// src/components/Home/Home.tsx
import './Home.css'
import About from '../About/About'
import Section from '../Section/Section'
import Item from '../Item/Item'
import manulife from '../../assets/images/manulife.png'
import seneca from '../../assets/images/seneca.png'
import ryerson from '../../assets/images/ryerson.png'
import andika from '../../assets/images/andika.png'
import tinystock from '../../assets/images/tinystock.png'
import tuma from '../../assets/images/tuma.png'
import Skills from '../Skills/Skills'

const Home = () => {
    return (
        <nav>
            <About />
            <Section id="work" title="Work">
                <Item
                    image={manulife}
                    title="Manulife Financial"
                    subtitle="Visiting Platform Reliability Engineer - Co-op"
                    BG="0b331b"
                    imageBG="1fa755"

                >
                    <small>September - December 2019</small>
                </Item>
                <Item
                    image={seneca}
                    title="Seneca College"
                    subtitle="Programmer - Co-op"
                    BG="470400"
                    imageBG="d60c00"
                >
                    <small>January - April 2019</small>
                </Item>
            </Section>
            <Section id="study" title="Study">
                <Item
                    image={ryerson}
                    title="Ryerson University"
                    subtitle="Computer Science (BSc)"
                    BG="001a35"
                    imageBG="004c9a"
                >
                    <small>September 2020 - December 2022</small>
                </Item>
                <Item
                    image={seneca}
                    title="Seneca College"
                    subtitle="Computer Programming and Analysis"
                    BG="470400"
                    imageBG="d60c00"
                >
                    <small>September 2017 - December 2020</small>
                </Item>
            </Section>
            <Section id="projects" title="Projects">
                <Item
                    image={andika}
                    title="Andika"
                    subtitle="Note taking Web App"
                    BG="111111"
                    imageBG="000000"
                >
                    <small><a href="https://github.com/ImranR98/andika" target="_blank" rel="noreferrer">GitHub</a></small>
                </Item>
                <Item
                    image={tinystock}
                    title="TinyStock"
                    subtitle="Minimal stock keeping Electron App"
                    BG="46091d"
                    imageBG="f21e65"
                >
                    <small><a href="https://github.com/ImranR98/TinyStock" target="_blank" rel="noreferrer">GitHub</a></small>
                </Item>
                <Item
                    image={tuma}
                    title="Tuma"
                    subtitle="Flutter App to Upload via SFTP"
                    BG="320d0b"
                    imageBG="f44236"
                >
                    <small><a href="https://github.com/ImranR98/Tuma" target="_blank" rel="noreferrer">GitHub</a></small>
                </Item>
            </Section>
            <Section id="skills" title="Skills">
                <Skills />
            </Section>
        </nav>
    );
};

export default Home;
