// src/components/Skills/Skills.tsx
import './Skills.css'
import Skill from './Skill//Skill'
import nodejs from '../../assets/images/nodejs.jpg'
import angular from '../../assets/images/angular.jpg'
import react from '../../assets/images/react.jpg'
import html from '../../assets/images/html.jpg'
import css from '../../assets/images/css.jpg'
import javascript from '../../assets/images/javascript.jpg'
import typescript from '../../assets/images/typescript.jpg'
import flutter from '../../assets/images/flutter.jpg'
import mongodb from '../../assets/images/mongodb.jpg'
import mysql from '../../assets/images/mysql.jpg'
import postgresql from '../../assets/images/postgresql.jpg'
import sublime from '../../assets/images/sublime.jpg'
import vs from '../../assets/images/vs.jpg'
import vscode from '../../assets/images/vscode.jpg'
import apigee from '../../assets/images/apigee.jpg'
import concourse from '../../assets/images/concourse.jpg'
import heroku from '../../assets/images/heroku.jpg'
import jira from '../../assets/images/jira.jpg'
import pcf from '../../assets/images/pcf.jpg'
import servicenow from '../../assets/images/servicenow.jpg'
import bash from '../../assets/images/bash.jpg'
import cpp from '../../assets/images/cpp.jpg'
import git from '../../assets/images/git.jpg'
import java from '../../assets/images/java.jpg'
import linux from '../../assets/images/linux.jpg'
import photoshop from '../../assets/images/photoshop.jpg'

const Skills = () => {
    return (
        <div className="skillGrid">
            <Skill alt="Node.js" image={nodejs}></Skill>
            <Skill alt="Angular" image={angular}></Skill>
            <Skill alt="React" image={react}></Skill>
            <Skill alt="HTML" image={html}></Skill>
            <Skill alt="CSS" image={css}></Skill>
            <Skill alt="JavaScript" image={javascript}></Skill>
            <Skill alt="TypeScript" image={typescript}></Skill>
            <Skill alt="Flutter" image={flutter}></Skill>
            <Skill alt="MongoDB" image={mongodb}></Skill>
            <Skill alt="MySQL" image={mysql}></Skill>
            <Skill alt="PostgreSQL" image={postgresql}></Skill>
            <Skill alt="Sublime Text" image={sublime}></Skill>
            <Skill alt="Microsoft Visual Studio" image={vs}></Skill>
            <Skill alt="Visual Studio Code" image={vscode}></Skill>
            <Skill alt="Apigee API Management" image={apigee}></Skill>
            <Skill alt="Concourse CI" image={concourse}></Skill>
            <Skill alt="Heroku" image={heroku}></Skill>
            <Skill alt="Jira" image={jira}></Skill>
            <Skill alt="Pivotal Cloud Foundry" image={pcf}></Skill>
            <Skill alt="ServiceNOW" image={servicenow}></Skill>
            <Skill alt="Bash Scripting" image={bash}></Skill>
            <Skill alt="C++" image={cpp}></Skill>
            <Skill alt="Git" image={git}></Skill>
            <Skill alt="Java" image={java}></Skill>
            <Skill alt="Linux/UNIX" image={linux}></Skill>
            <Skill alt="Adobe Photoshop" image={photoshop}></Skill>
        </div>
    );
};

export default Skills;

// client/src/app/skills/skills.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-skills',
  templateUrl: './skills.component.html',
  styleUrls: ['./skills.component.sass']
})
export class SkillsComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  skills: string = '../../assets/skills.png';

}

<div fxLayout="column">
  <app-title [bgImage]=skills [matIcon]="'emoji_symbols'" [title]="'Skills'"></app-title>
  <mat-card class="stdMargin" fxLayout="row-wrap" fxLayout.lt-sm="column" fxLayoutAlign="start start center"
    fxLayoutAlign.lt-sm="center start center" fxLayoutGap="2em" fxLayoutGap.lt-sm="0em">
    <div>
      <div fxLayout="column" fxLayoutGap="1em">
        <span>Web Development</span>
        <div>
          <mat-card-subtitle>Angular</mat-card-subtitle>
          <mat-card-subtitle>Node.js</mat-card-subtitle>
          <mat-card-subtitle>Express.js</mat-card-subtitle>
          <mat-card-subtitle>React</mat-card-subtitle>
          <mat-card-subtitle>jQuery</mat-card-subtitle>
          <mat-card-subtitle>AJAX</mat-card-subtitle>
          <mat-card-subtitle>REST APIs</mat-card-subtitle>
        </div>
      </div>
      <mat-divider [inset]="true"></mat-divider>
      <br>
      <div fxLayout="column" fxLayoutGap="1em">
        <span>Languages</span>
        <div>
          <mat-card-subtitle>Javascript</mat-card-subtitle>
          <mat-card-subtitle>C++ / C</mat-card-subtitle>
          <mat-card-subtitle>TypeScript</mat-card-subtitle>
          <mat-card-subtitle>SQL</mat-card-subtitle>
          <mat-card-subtitle>Java</mat-card-subtitle>
          <mat-card-subtitle>CLLE</mat-card-subtitle>
          <mat-card-subtitle>RPGLE</mat-card-subtitle>
        </div>
      </div>
      <mat-divider [inset]="true" fxHide fxShow.lt-sm></mat-divider>
      <br>
    </div>
    <div>
      <div fxLayout="column" fxLayoutGap="1em">
        <span>Database Management</span>
        <div>
          <mat-card-subtitle>PostgreSQL</mat-card-subtitle>
          <mat-card-subtitle>MongoDB</mat-card-subtitle>
          <mat-card-subtitle>Oracle 12c</mat-card-subtitle>
          <mat-card-subtitle>MySQL</mat-card-subtitle>
          <mat-card-subtitle>IBM DB2</mat-card-subtitle>
        </div>
      </div>
      <mat-divider [inset]="true"></mat-divider>
      <br>
      <div fxLayout="column" fxLayoutGap="1em">
        <span>Development Tools</span>
        <div>
          <mat-card-subtitle>Visual Studio</mat-card-subtitle>
          <mat-card-subtitle>Visual Studio Code</mat-card-subtitle>
          <mat-card-subtitle>Eclipse</mat-card-subtitle>
          <mat-card-subtitle>Sublime</mat-card-subtitle>
        </div>
      </div>
      <mat-divider [inset]="true" fxHide fxShow.lt-sm></mat-divider>
      <br>
    </div>
    <div>
      <div fxLayout="column" fxLayoutGap="1em">
        <span>Platform</span>
        <div>
          <mat-card-subtitle>Pivotal Cloud Foundry</mat-card-subtitle>
          <mat-card-subtitle>Concourse CI</mat-card-subtitle>
          <mat-card-subtitle>Apigee API Management</mat-card-subtitle>
          <mat-card-subtitle>Jira</mat-card-subtitle>
          <mat-card-subtitle>ServiceNow</mat-card-subtitle>
          <mat-card-subtitle>Heroku</mat-card-subtitle>
          <mat-card-subtitle>Azure DevOps</mat-card-subtitle>
        </div>
      </div>
      <mat-divider [inset]="true"></mat-divider>
      <br>
      <div fxLayout="column" fxLayoutGap="1em">
        <span>Other</span>
        <div>
          <mat-card-subtitle>Git</mat-card-subtitle>
          <mat-card-subtitle>Angular Material</mat-card-subtitle>
          <mat-card-subtitle>NgRx</mat-card-subtitle>
          <mat-card-subtitle>HTML / CSS</mat-card-subtitle>
          <mat-card-subtitle>Adobe Photoshop</mat-card-subtitle>
        </div>
      </div>
      <mat-divider [inset]="true" fxHide fxShow.lt-sm></mat-divider>
      <br>
    </div>
  </mat-card>
</div>
